[build]
# Para ARM64 no Railway: instala Chromium + Chromedriver do sistema
nixPkgs = [
  "chromium",
  "chromedriver",
  # DEPENDÃŠNCIAS ESSENCIAIS PARA EXECUTAR O CHROME EM HEADLESS NO LINUX:
  "libnss", 
  "libgconf",
  "libxss", 
  "alsa-lib",
  "nss"
]

[deploy]
startCommand = "python main.py"