[build]
# Para ARM64 no Railway: instala Chromium + Chromedriver do sistema
nixPkgs = [
  "chromium",
  "chromedriver",
  # DependÃªncias essenciais para o ChromeDriver rodar em ambiente Linux/headless:
  "libnss", 
  "libgconf",
  "libxss", 
  "alsa-lib",
  "nss"
]

[deploy]
startCommand = "python main.py"
